spring:
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8081
  tomcat:
    max-http-header-size: 65536

gateway:
  base-url: http://136.115.53.140:5000
